#!/usr/bin/env bash
#process and pid file
pid_file="/var/run/myscript.pid"
function delete_pidfile () {
    rm "$pid_file"
    exit
}
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!;delete_pidfile" SIGINT
echo $$ >> $pid_file
while true; do
    echo "To infinity and beyond";
    sleep 2;
done
