#!/usr/bin/env bash
#Manages the file "manage my process"
#shellcheck disable=SC2009
# Function to write "I am alive!" to the file /tmp/my_process
write_to_file() {
    echo "I am alive!" >> /tmp/my_process
}

# Function to start the process
start_process() {
    # Start the process in the background
    while true
    do
        write_to_file
        sleep 2
    done &
    
    # Get the process ID and save it to a file
    echo $! > /var/run/my_process.pid
    
    echo "manage_my_process started"
}

# Function to stop the process
stop_process() {
    # Read the process ID from the file
    if [ -f "/var/run/my_process.pid" ]; then
        pid=$(cat /var/run/my_process.pid)
        
        # Kill the process
        kill $pid
        
        # Remove the PID file
        rm /var/run/my_process.pid
        
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

# Function to restart the process
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

# Main script logic
if [ "$1" == "start" ]; then
    start_process
elif [ "$1" == "stop" ]; then
    stop_process
elif [ "$1" == "restart" ]; then
    restart_process
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
