#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond
# Finding the process ID of 4-to_infinity_and_beyond
pid=$(pgrep 4-to_infinity_and_beyond )
# Kill the process
  kill "$pid"
