#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process.
pkill -f "4-to_infinity_and_beyond"
if [ $? -eq 0 ]; then
    echo "4-to_infinity_and_beyond process stopped."
else
    echo "4-to_infinity_and_beyond process is not running."
fi
