#!/usr/bin/env bash
# kills the process 7-highlander.
pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    echo "Stopping 7-highlander process (PID: $pid)..."
     kill $pid
else
    echo "7-highlander process is not running."
fi
